name = Newsitem
description = display of one news item
template = newsitem-layout

; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[contentlayer2] = Content Layer 2
regions[sidebar_first] = First Sidebar
regions[footer] = Footer
